// <auto-generated />
using FuzzySearchApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FuzzySearchApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "fuzzystrmatch");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FuzzySearchApi.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Name = "Azamjon"
                        },
                        new
                        {
                            Id = 2,
                            Age = 18,
                            Name = "MuhammadDiyor"
                        },
                        new
                        {
                            Id = 3,
                            Age = 26,
                            Name = "Nuriddin"
                        },
                        new
                        {
                            Id = 4,
                            Age = 17,
                            Name = "Abdulaziz"
                        },
                        new
                        {
                            Id = 5,
                            Age = 26,
                            Name = "Umidbek"
                        },
                        new
                        {
                            Id = 6,
                            Age = 20,
                            Name = "Botirjon"
                        },
                        new
                        {
                            Id = 7,
                            Age = 19,
                            Name = "Jamoliddin"
                        },
                        new
                        {
                            Id = 8,
                            Age = 23,
                            Name = "Shaxzod"
                        },
                        new
                        {
                            Id = 9,
                            Age = 25,
                            Name = "Javlon"
                        },
                        new
                        {
                            Id = 10,
                            Age = 26,
                            Name = "Abduvohid"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
